config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
    
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 2)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article was successfully created."
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article updated successfully!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was successfully deleted."
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description, category_ids: [])
		end

		def require_same_user
			if current_user != @article.user && !current_user.admin?
				flash[:danger] = "You can only edit or delete your own article."
				redirect_to root_path
			end
		end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 2)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully."
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "The category was updated successfully."
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 2)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action."
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in."
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, except: [:index, :show, :new, :create]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}."
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Account Updated."
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User and all articles created by by user have been deleted."
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit your own account."
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin users can perform this action."
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% object.each do |article| %>
  <div class="row">
    <div class="col-xs-8">
      <div class="well">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created By: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) + " ago" %>, Last Updated: <%= time_ago_in_words(article.updated_at) + " ago" %></small>
          </div>
        </div>

        <% if article.categories.any? %>
          <%= render article.categories %>
        <% end %>

        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete Article", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', object: @article %>

<div class="row">
	<div class="col-xs-8">
		<%= form_for @article do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article" %>
			</div>
			<div class="form-group">
				<%= f.collection_check_boxes :category_ids, Category.order(:name), :id, :name do |cb| %>
					<%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
				<% end %>
			</div>
			<div class="form-group">
				<%= f.submit class: "btn btn-primary btn-lg" %>
				<%= link_to "Cancel", articles_path, class: "btn btn-danger btn-lg" %>
			</div>
		<% end %>

	</div>
</div>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Edit Article</h1>
  </div>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Articles</h1>
  </div>
</div>

<%= render 'article', object: @articles %>

<%= will_paginate %>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Create Article</h1>
  </div>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @article.title %></h1>
  </div>
</div>

<div class="well col-xs-8">

  <%= simple_format(@article.description) %>

  <% if @article.categories.any? %>
    <%= render @article.categories %>
  <% end %>

  <% if @article.user %>
  <div class="user-body">
    <div class="user-title">
      <%= link_to gravatar_for(@article.user, 50), user_path(@article.user) %>
      <%= link_to @article.user.username.titleize, user_path(@article.user) %>
    </div>
  </div>
  <% end %>

  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-info" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-success">
  <%= link_to category.name, category_path(category) %>
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category %>

<div class="row">
	<div class="col-xs-8">
		<%= form_for @category do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control", placeholder: "Name of Category", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.submit class: "btn btn-primary btn-lg" %>
				<%= link_to "Cancel", categories_path, class: "btn btn-danger btn-lg" %>
			</div>
		<% end %>

	</div>
</div>

app/views/categories/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Edit Category</h1>
  </div>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Categories</h1>
  </div>
</div>

<% @categories.each do |category| %>
  <div class="row">
    <div class="col-xs-8">
      <div class="well">
        <div class="article-title">
          <%= link_to "#{category.name}", category_path(category) %>
        </div>
        <small><%= pluralize(category.articles.count, "article") %>.</small>
      </div>
    </div>
  </div>
<% end %>

<%= will_paginate %>

app/views/categories/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Create Category</h1>
  </div>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @category.name %></h1>
    <% if logged_in? && current_user.admin? %>
      <%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-xs btn-primary m-b-10" %>
    <% end %>
  </div>
</div>

<%= render 'articles/article', object: @category_articles %>

<%= will_paginate @category_articles %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyright &copy; Alpha Blog 2019</small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

<%= debug(params) if Rails.env.development? %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %> 
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.order(:name).each do |category| %>
              <li><%= link_to category.name.titleize, category_path(category) %></li>
            <% end %>
            <% if logged_in? && current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Add Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Users", users_path %></li>

        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.admin? ? "Admin" : "My Profile" %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About!</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG!!!!</h1>
  <%= link_to "Sign Up Now", signup_path, class: "btn btn-primary btn-lg btn-special" %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<div class="row">
		<div class="col-xs-8">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(object.errors.count, "error") %>
						prohibited this <%= object.class.name.downcase %> from being saved.
					</h2>
				</div>
				<div class="panel-body">
					<ul>
						<% object.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>

<div class="row">
	<div class="col-xs-8">
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :username %>
				<%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, class: "form-control", placeholder: "Enter Email", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary btn-lg") %>
			</div>
		<% end %>

	</div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Edit Account</h1>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Alpha Bloggers</h1>
  </div>
</div>

<% @users.each do |user| %>
  <div class="row">
    <div class="col-xs-8">
      <div class="well">
        <div class="user-title">
          <%= link_to gravatar_for(user, 150), user_path(user) %>
          <%= link_to user.username.titleize, user_path(user) %>
        </div>
        <div class="user-body">
          <div class="article-meta-details">
            <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
          </div>
        </div>

        <% if logged_in? && current_user.admin? %>
          <div class="article-actions">
            <%= link_to "Delete User", user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Sign Up</h1>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Welcome to <%= @user.username.titleize %>'s Page</h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-8">
    <%= gravatar_for @user, 150  %>
  </div>
</div>

<h4>Articles by <%= @user.username.titleize %></h4>

<%= render 'articles/article', object: @user_articles %>

<%= will_paginate(@user_articles) %>